Models/Rezervare.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackWalkLicenta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rezervare
    {
        public int RezervareId { get; set; }
        [Required]
        [Display(Name = "Adresa de ridicare")]
        public string Adresa_de_Ridicare { get; set; }
        [Required]
        [Display(Name = "Telefonul expeditorului")]
        public string Numarul_persoanei_care_trimite { get; set; }
        [Required]
        [Display(Name = "Adresa de predare")]
        public string Adresa_de_Predare { get; set; }
        [Required]
        [Display(Name = "Telefonul destinatarului")]
        public string Numarul_persoanei_care_primeste { get; set; }
        [Required]
        [Display(Name = "Greutatea aproximativă")]
        public string Cantitate_aproximativa { get; set; }
        [Required]
        //[DataType(DataType.Date)]
        [Display(Name="Data trimiterii")]
        public Nullable<System.DateTime> Data_Trimiterii { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}

Controllers/RezervaresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using PackWalkLicenta.Models;
using PackWalkLicenta.Models.ViewModels;

namespace PackWalkLicenta.Controllers
{
    public class RezervaresController : Controller
    {
        private PackWalkDbEntities db = new PackWalkDbEntities();

        // GET: Rezervares
        public ActionResult Index()
        {
            return View(db.Rezervares.ToList());
        }

        // GET: Rezervares/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervare rezervare = db.Rezervares.Find(id);
            if (rezervare == null)
            {
                return HttpNotFound();
            }
            return View(rezervare);
        }

        // GET: Rezervares/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rezervares/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RezervareId,Adresa_de_Ridicare,Numarul_persoanei_care_trimite,Adresa_de_Predare,Numarul_persoanei_care_primeste,Cantitate_aproximativa,Data_Trimiterii")] Rezervare rezervare)
        {
            if (ModelState.IsValid)
            {
                rezervare.UserId = int.Parse(Session["UserId"].ToString());
                db.Rezervares.Add(rezervare);
                db.SaveChanges();
                return RedirectToAction("RezervareSucces");
            }

            return View(rezervare);
        }
        public ActionResult RezervareSucces()
        {
            return View();
        }
    
        // GET: Rezervares/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervare rezervare = db.Rezervares.Find(id);
            if (rezervare == null)
            {
                return HttpNotFound();
            }
            return View(rezervare);
        }

        // POST: Rezervares/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RezervareId,Adresa_de_Ridicare,Numarul_persoanei_care_trimite,Adresa_de_Predare,Numarul_persoanei_care_primeste,Cantitate_aproximativa,Data_Trimiterii")] Rezervare rezervare)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervare).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rezervare);
        }

        // GET: Rezervares/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervare rezervare = db.Rezervares.Find(id);
            if (rezervare == null)
            {
                return HttpNotFound();
            }
            return View(rezervare);
        }

        // POST: Rezervares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervare rezervare = db.Rezervares.Find(id);
            db.Rezervares.Remove(rezervare);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult SendEmail(int? id)
        {
            Rezervare rezervare = db.Rezervares.Find(id);

            return View(new EmailContent {RezervareID=rezervare.RezervareId,Destinatar=rezervare.User.Email,Subiect=$"Informare cu privire la rezervarea din data {rezervare.Data_Trimiterii}" });
        }
        [HttpPost]
        public ActionResult SendEmail(EmailContent email)
        {
            try
            {
                if (ModelState.IsValid)
                { 
                    var senderEmail = new MailAddress("pachete.studentesti12@gmail.com", "PackWalk-Plimbarea Pachetelor");
                    var receiverEmail = new MailAddress(email.Destinatar, "Receiver");
                    var password = "Licenta1234";
                    var sub = email.Subiect;
                    var body = email.Mesaj;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)
                    };
                    using (var mess = new MailMessage(senderEmail, receiverEmail)
                    {
                        Subject = sub,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }
                    return RedirectToAction("EmailSucces");
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Ceva a fost în neregulă! Ne pare rău, mail-ul nu s-a putut trimite. Încercați din nou!";
            }
            return View();
        }
        public ActionResult EmailSucces()
        {
            return View();
        }
    }
}

Views/Rezervares/Create.cshtml
@model PackWalkLicenta.Models.Rezervare

@{
    ViewBag.Title = "Create";
}

<link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/themes/dot-luv/jquery-ui.css" rel="stylesheet" />

@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        //functie prin care data se preia sub forma de calendar
        $(document).ready(function () {
            $("#Data_Trimiterii").datepicker();
        });
        //functie care are ca rol dezactivarea sugestiilor
        $(document).ready(function () {
            $("input:text,form").attr("autocomplete", "off");
        })
    </script>

   }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <br />
    
    <img style="width:500px; height:300px" src="~/Content/themes/base/images/rezervare2.jpg" />
    <br/>
    <br/>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Adresa_de_Ridicare, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresa_de_Ridicare, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresa_de_Ridicare, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numarul_persoanei_care_trimite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numarul_persoanei_care_trimite, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Numarul_persoanei_care_trimite, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adresa_de_Predare, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresa_de_Predare, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresa_de_Predare, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numarul_persoanei_care_primeste, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numarul_persoanei_care_primeste, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Numarul_persoanei_care_primeste, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantitate_aproximativa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantitate_aproximativa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantitate_aproximativa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Data_Trimiterii, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.EditorFor(model => model.Data_Trimiterii, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Data_Trimiterii, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Rezervă" class="btn btn-default" />
        </div>
    </div>
</div>
    }

   

Views/Rezervares/Delete.cshtml
@model PackWalkLicenta.Models.Rezervare

@{
    ViewBag.Title = "Delete";
}

<h2>Șterge înregistrarea</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adresa_de_Ridicare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa_de_Ridicare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numarul_persoanei_care_trimite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numarul_persoanei_care_trimite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa_de_Predare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa_de_Predare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numarul_persoanei_care_primeste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numarul_persoanei_care_primeste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantitate_aproximativa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantitate_aproximativa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_Trimiterii)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_Trimiterii)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Șterge" class="btn btn-default" /> 
          
        </div>
    }
<div style="text-align:right"> 
    @Html.ActionLink("Înapoi la lista de rezervări", "Index")
</div>
</div>

Views/Rezervares/EmailSucces.cshtml
@{
    ViewBag.Title = "EmailSucces";
}

<h2 style="text-align:center">Email trimis cu succes!</h2>
<img style="margin-left:450px" src="~/Content/themes/base/images/pachettt.jpg" />
<br />
<div style="text-align:right">
    <h4> @Html.ActionLink("Înapoi la lista de rezervări", "Index", "Rezervares") </h4>
</div>

Views/Rezervares/Index.cshtml
@model IEnumerable<PackWalkLicenta.Models.Rezervare>

@{
    ViewBag.Title = "Index";
}


    <div style="text-align:center">
        <h1 style="text-align:center">Listă de rezervări</h1>
        <img src="~/Content/themes/base/images/pachettt.jpg" />
    </div>

<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Nume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Prenume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa_de_Ridicare)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numarul_persoanei_care_trimite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa_de_Predare)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numarul_persoanei_care_primeste)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantitate_aproximativa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_Trimiterii)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.Nume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Prenume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresa_de_Ridicare)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numarul_persoanei_care_trimite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresa_de_Predare)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numarul_persoanei_care_primeste)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantitate_aproximativa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_Trimiterii)
            </td>
            <td>
                @Html.ActionLink("Șterge rezervarea", "Delete", new { id = item.RezervareId })|
                @Html.ActionLink("Trimite mail de transmitere a orei", "SendEmail", new { id = item.RezervareId })
            </td>
        </tr>
    }

</table>
<br />
<br />
<table>
    <tr>
        <td>

            @Html.ActionLink("Înapoi la meniul administratorului", "ViewAdmin", "Home") |

            @Html.ActionLink("Ieșire din cont", "Logout", "Home")

        </td>
    </tr>
</table>

Views/Rezervares/RezervareSucces.cshtml
@{
    ViewBag.Title = "RezervareSucces";
}

<h2 style="text-align:center">Rezervare efectuată cu succes!</h2>
<h2 style="text-align:center">Mulțumim și vă mai așteptăm pe pagina noastră!</h2>
<br/>
<img style="margin-left:250px" src="~/Content/themes/base/images/gluma.jpg" />
<br/>
<div style="text-align:right">
   <h4> @Html.ActionLink("Ieșire din cont", "Logout", "Home") </h4>
</div>

Views/Rezervares/SendEmail.cshtml
@model PackWalkLicenta.Models.ViewModels.EmailContent

@{
    ViewBag.Title = "SendEmail";
}
@section Scripts {

    <script>
        //functie care are ca rol dezactivarea sugestiilor
        $(document).ready(function () {
            $("input:text,form").attr("autocomplete", "off");
        })
    </script>

}
<div style="margin-left:100px">
    <h2>Trimitere mail de notificare</h2>
    <img src="~/Content/themes/base/images/inmanarea.jpg" />
    <br />
    <br />
</div>
@if (ViewBag.Error != null)
{
    <h2> @ViewBag.Error </h2>

}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RezervareID)

        <div class="form-group">
            @Html.LabelFor(model => model.Destinatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destinatar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destinatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subiect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subiect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subiect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mesaj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mesaj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mesaj, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Trimite Email" class="btn btn-default" />
            </div>
        </div>
    </div>
}